environment:
 VK_SDK_PATH: "C:\\VulkanSDK\\1.1.85.0"
 VULKAN_SDK: "C:\\VulkanSDK\\1.1.85.0"
 EIGEN_DIR: "C:\\Eigen"
version: '1.0.0.{build}'

image:
 - Visual Studio 2017

clone_depth: 1

cache:
  - C:\VulkanSDK\1.1.85.0\Bin -> appveyor.yml
  - C:\VulkanSDK\1.1.85.0\Bin32 -> appveyor.yml
  - C:\VulkanSDK\1.1.85.0\Include -> appveyor.yml
  - C:\VulkanSDK\1.1.85.0\Source\lib -> appveyor.yml
  - C:\VulkanSDK\1.1.85.0\Source\lib32 -> appveyor.yml
  - C:\VulkanSDK\1.1.85.0\spirv-tools -> appveyor.yml
  - C:\Eigen -> appveyor.yml

install:
 # Download and Install Vulkan SDK
 - ps: if(!(Test-Path C:\VulkanSDK)) { Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.1.85.0/windows/VulkanSDK-1.1.85.0-Installer.exe?Human=true -OutFile vulkan.exe }
 - IF NOT EXIST C:\VulkanSDK ( vulkan.exe /S )
 # Download Eigen
 - ps: if(!(Test-Path C:\Eigen\Eigen)) { Invoke-WebRequest -Uri http://bitbucket.org/eigen/eigen/get/3.3.7.zip  -OutFile eigen.zip }
 - ps: if(!(Test-Path C:\Eigen\Eigen)) { Expand-Archive ./eigen.zip -DestinationPath . }
 - ps: if(!(Test-Path C:\Eigen\Eigen)) { mkdir C:\Eigen }
 - ps: if(!(Test-Path C:\Eigen\Eigen)) { cd eigen-* }
 - ps: if(!(Test-Path C:\Eigen\Eigen)) { move Eigen C:\Eigen\Eigen }
# Create build folders
 - ps: if(!(Test-Path C:\VK9-x86-Release)) { mkdir C:\VK9-x86-Release }
 - ps: if(!(Test-Path C:\VK9-x64-Release)) { mkdir C:\VK9-x64-Release }
 # go back into the build dir
 - ps: pushd "C:\projects\vk9\"

build_script:
 - ps: echo $ENV:VULKAN_SDK
 - ps: $Env:PLATFORM_TOOLSET="v141"
 - msbuild VK9.sln /t:VK9-Library /p:Configuration=Release;Platform=Win32 /p:PlatformToolset=%PLATFORM_TOOLSET% /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
 - ps: copy C:\projects\vk9\Release\d3d9.dll "C:\VK9-x86-Release\d3d9.dll"
 - ps: copy C:\projects\vk9\Release\d3d9.pdb "C:\VK9-x86-Release\d3d9.pdb"
 - ps: copy C:\projects\vk9\VK9-Library\VK9.conf "C:\VK9-x86-Release\VK9.conf"
 - 7z a C:\VK9-x86-Release.zip C:\VK9-x86-Release
 - msbuild VK9.sln /t:VK9-Library /p:Configuration=Release;Platform=x64 /p:PlatformToolset=%PLATFORM_TOOLSET% /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
 - ps: copy C:\projects\vk9\x64\Release\d3d9.dll "C:\VK9-x64-Release\d3d9.dll"
 - ps: copy C:\projects\vk9\x64\Release\d3d9.pdb "C:\VK9-x64-Release\d3d9.pdb"
 - ps: copy C:\projects\vk9\VK9-Library\VK9.conf "C:\VK9-x64-Release\VK9.conf"
 - 7z a C:\VK9-x64-Release.zip C:\VK9-x64-Release

after_build:
 - ps: Push-AppveyorArtifact "C:\VK9-x86-Release.zip"
 - ps: Push-AppveyorArtifact "C:\VK9-x64-Release.zip"

